/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_certora_wala_cast_solidity_jni_SolidityJNIBridge_SolidityFileTranslator */

#ifndef _Included_com_certora_wala_cast_solidity_jni_SolidityJNIBridge_SolidityFileTranslator
#define _Included_com_certora_wala_cast_solidity_jni_SolidityJNIBridge_SolidityFileTranslator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_certora_wala_cast_solidity_jni_SolidityJNIBridge_SolidityFileTranslator
 * Method:    translate
 * Signature: (Ljava/lang/String;)Lcom/ibm/wala/cast/tree/CAstEntity;
 */
JNIEXPORT jobject JNICALL Java_com_certora_wala_cast_solidity_jni_SolidityJNIBridge_00024SolidityFileTranslator_translate
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
