/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_certora_wala_cast_solidity_jni_SolidityJNIBridge */

#ifndef _Included_com_certora_wala_cast_solidity_jni_SolidityJNIBridge
#define _Included_com_certora_wala_cast_solidity_jni_SolidityJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_certora_wala_cast_solidity_jni_SolidityJNIBridge
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_certora_wala_cast_solidity_jni_SolidityJNIBridge_init
  (JNIEnv *, jobject);

/*
 * Class:     com_certora_wala_cast_solidity_jni_SolidityJNIBridge
 * Method:    loadFiles
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_certora_wala_cast_solidity_jni_SolidityJNIBridge_loadFiles
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_certora_wala_cast_solidity_jni_SolidityJNIBridge
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_certora_wala_cast_solidity_jni_SolidityJNIBridge_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
